# Generated by Django 5.1.1 on 2024-12-10 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokeAPP', '0010_alter_tarea_hora_anclaje_alter_tarea_hora_venconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='cordenadas',
            field=models.CharField(default='cordenadas pendiente', max_length=255),
        ),
    ]
