# Generated by Django 5.1.1 on 2024-12-10 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokeAPP', '0012_alter_tarea_fecha_anclaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='fecha_anclaje',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
