# Generated by Django 5.1.1 on 2024-12-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokeAPP', '0015_alter_tarea_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('iniciado', 'Iniciado'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado'), ('pendiente_revision', 'Pendiente de Revisión'), ('reasignado', 'Reasignado')], default='pendiente', max_length=20),
        ),
    ]
