# Generated by Django 5.1.1 on 2025-01-06 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brokeAPP', '0018_alter_notificacion_tarea_alter_notificacion_usuario'),
        ('brokeAPP', '0022_alter_salario_fecha_pago'),
    ]

    operations = [
    ]
