# Generated by Django 5.1.1 on 2025-01-06 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokeAPP', '0023_merge_20250106_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salario',
            name='pago_actividad',
        ),
        migrations.RemoveField(
            model_name='salario',
            name='total_pago',
        ),
        migrations.AddField(
            model_name='salario',
            name='pago_sitio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salario',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='salario',
            name='viaticos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
