# Generated by Django 5.1.1 on 2024-10-31 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokeAPP', '0002_alter_usuariocustomizado_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='num_cajero',
            field=models.CharField(default='0', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarea',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
    ]
