# Generated by Django 5.1.1 on 2024-10-31 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokeAPP', '0003_tarea_num_cajero_tarea_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='num_cajero',
            field=models.CharField(default='Sin número', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
