# Generated by Django 5.1.1 on 2024-12-10 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokeAPP', '0005_tarea_completada'),
    ]

    operations = [
        migrations.CreateModel(
            name='TareaAvanzada',
            fields=[
                ('tarea_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='brokeAPP.tarea')),
                ('prioridad', models.CharField(choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')], default='Media', max_length=50)),
                ('responsable', models.CharField(blank=True, max_length=100, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
            ],
            bases=('brokeAPP.tarea',),
        ),
        migrations.AddField(
            model_name='tarea',
            name='Cod_postal',
            field=models.CharField(default='Dirección pendiente', max_length=255),
        ),
        migrations.AddField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('iniciado', 'Iniciado'), ('en_proceso', 'En Proceso'), ('completado', 'Completado')], default='iniciado', max_length=20),
        ),
    ]
