# Generated by Django 5.1.1 on 2024-12-10 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokeAPP', '0009_alter_tarea_fecha_anclaje_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='hora_anclaje',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='hora_venconfig',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
