# Generated by Django 5.1.1 on 2024-12-18 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokeAPP', '0017_remove_notificacion_fecha_remove_notificacion_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brokeAPP.tarea'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
