# Generated by Django 5.1.1 on 2024-12-17 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokeAPP', '0018_historialtarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialtarea',
            name='fecha_asignacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
