# Generated by Django 5.1.1 on 2024-12-18 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brokeAPP', '0019_alter_historialtarea_fecha_asignacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salario',
            name='lugar_trabajo',
        ),
    ]
