# Generated by Django 5.1.1 on 2024-12-18 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokeAPP', '0020_remove_salario_lugar_trabajo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('iniciado', 'Iniciado'), ('en_proceso', 'En Proceso'), ('Anclaje_completado', 'Anclaje completado'), ('cancelado', 'Cancelado'), ('completado', 'Completado'), ('pendiente_revision', 'Pendiente de Revisión'), ('reprogramado', 'Reprogramado')], default='pendiente', max_length=20),
        ),
    ]
