# Generated by Django 5.1.1 on 2024-12-18 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokeAPP', '0021_alter_tarea_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salario',
            name='fecha_pago',
            field=models.DateField(auto_now_add=True),
        ),
    ]
