# Generated by Django 5.1.1 on 2025-01-08 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokeAPP', '0025_tarea_confirmacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salario',
            name='fecha_pago',
        ),
        migrations.AlterField(
            model_name='tarea',
            name='confirmacion',
            field=models.CharField(choices=[('sin_confirmar', 'Sin Confirmar'), ('confirmado', 'Confirmado'), ('rechazado', 'Rechazado')], default='sin_confirmar', max_length=50),
        ),
    ]
